"""Small built-in movie catalog used by the recommendation system."""

MOVIES = [
    {
        "id": "m1",
        "title": "Inception",
        "type": "Movie",
        "year": 2010,
        "rating": 8.8,
        "genres": ["Sci-Fi", "Action", "Thriller"],
        "moods": ["Mind-Bending", "Adrenaline", "Philosophical"],
        "director": "Christopher Nolan",
        "duration": "2h 28m",
        "overview": "A thief who enters dreams is asked to plant an idea in a target's mind.",
        "poster": "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&auto=format&fit=crop&q=80",
        "backdrop": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80",
        "streaming": ["Netflix", "Max", "Prime Video"],
    },
    {
        "id": "m2",
        "title": "Interstellar",
        "type": "Movie",
        "year": 2014,
        "rating": 8.7,
        "genres": ["Sci-Fi", "Drama", "Adventure"],
        "moods": ["Mind-Bending", "Emotional", "Epic"],
        "director": "Christopher Nolan",
        "duration": "2h 49m",
        "overview": "Explorers travel through a wormhole to find a new home for humanity.",
        "poster": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80",
        "backdrop": "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=1600&auto=format&fit=crop&q=80",
        "streaming": ["Paramount+", "Prime Video"],
    },
    {
        "id": "m3",
        "title": "Severance",
        "type": "Series",
        "year": 2022,
        "rating": 8.7,
        "genres": ["Sci-Fi", "Thriller", "Mystery", "Drama"],
        "moods": ["Mind-Bending", "Dark", "Dystopian"],
        "director": "Ben Stiller",
        "duration": "2 Seasons",
        "overview": "Office workers split their work memories from their personal lives.",
        "poster": "https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800&auto=format&fit=crop&q=80",
        "backdrop": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1600&auto=format&fit=crop&q=80",
        "streaming": ["Apple TV+"],
    },
    {
        "id": "m4",
        "title": "The Dark Knight",
        "type": "Movie",
        "year": 2008,
        "rating": 9.0,
        "genres": ["Action", "Crime", "Drama"],
        "moods": ["Dark", "Adrenaline", "Epic"],
        "director": "Christopher Nolan",
        "duration": "2h 32m",
        "overview": "Batman faces a criminal mastermind determined to plunge Gotham into chaos.",
        "poster": "https://images.unsplash.com/photo-1509281373149-e957c6296406?w=800&auto=format&fit=crop&q=80",
        "backdrop": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
        "streaming": ["Max", "Netflix"],
    },
    {
        "id": "m5",
        "title": "Everything Everywhere All at Once",
        "type": "Movie",
        "year": 2022,
        "rating": 8.0,
        "genres": ["Sci-Fi", "Comedy", "Adventure", "Action"],
        "moods": ["Mind-Bending", "Feel-Good", "Emotional"],
        "director": "Daniel Kwan and Daniel Scheinert",
        "duration": "2h 19m",
        "overview": "A laundromat owner becomes an unlikely hero across many universes.",
        "poster": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80",
        "backdrop": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
        "streaming": ["Netflix", "Prime Video"],
    },
    {
        "id": "m6",
        "title": "Stranger Things",
        "type": "Series",
        "year": 2016,
        "rating": 8.7,
        "genres": ["Sci-Fi", "Horror", "Drama", "Fantasy"],
        "moods": ["Nostalgic", "Adrenaline", "Dark"],
        "director": "The Duffer Brothers",
        "duration": "5 Seasons",
        "overview": "Friends uncover secret experiments and supernatural forces in their town.",
        "poster": "https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?w=800&auto=format&fit=crop&q=80",
        "backdrop": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
        "streaming": ["Netflix"],
    },
    {
        "id": "m7",
        "title": "The Batman",
        "type": "Movie",
        "year": 2022,
        "rating": 7.9,
        "genres": ["Crime", "Drama", "Mystery", "Action"],
        "moods": ["Dark", "Moody", "Philosophical"],
        "director": "Matt Reeves",
        "duration": "2h 56m",
        "overview": "Batman follows a trail of clues left by a serial killer in Gotham.",
        "poster": "https://images.unsplash.com/photo-1509281373149-e957c6296406?w=800&auto=format&fit=crop&q=80",
        "backdrop": "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=1600&auto=format&fit=crop&q=80",
        "streaming": ["Max"],
    },
    {
        "id": "m8",
        "title": "Dune: Part Two",
        "type": "Movie",
        "year": 2024,
        "rating": 8.6,
        "genres": ["Sci-Fi", "Adventure", "Action", "Drama"],
        "moods": ["Epic", "Mind-Bending", "Adrenaline"],
        "director": "Denis Villeneuve",
        "duration": "2h 46m",
        "overview": "Paul Atreides joins the Fremen while seeking revenge for his family.",
        "poster": "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80",
        "backdrop": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80",
        "streaming": ["Max", "Prime Video"],
    },
    {
        "id": "m9",
        "title": "Spider-Man: Across the Spider-Verse",
        "type": "Movie",
        "year": 2023,
        "rating": 8.7,
        "genres": ["Animation", "Action", "Adventure", "Sci-Fi"],
        "moods": ["Feel-Good", "Mind-Bending", "Adrenaline"],
        "director": "Joaquim Dos Santos",
        "duration": "2h 20m",
        "overview": "Miles Morales journeys across the multiverse and meets new heroes.",
        "poster": "https://images.unsplash.com/photo-1635805737707-575885ab0820?w=800&auto=format&fit=crop&q=80",
        "backdrop": "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1600&auto=format&fit=crop&q=80",
        "streaming": ["Netflix"],
    },
    {
        "id": "m10",
        "title": "The Last of Us",
        "type": "Series",
        "year": 2023,
        "rating": 8.8,
        "genres": ["Drama", "Sci-Fi", "Horror", "Action"],
        "moods": ["Emotional", "Dark", "Post-Apocalyptic"],
        "director": "Craig Mazin and Neil Druckmann",
        "duration": "2 Seasons",
        "overview": "A survivor escorts a teenager across a dangerous post-pandemic America.",
        "poster": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80",
        "backdrop": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80",
        "streaming": ["Max"],
    },
    {
        "id": "m11",
        "title": "Parasite",
        "type": "Movie",
        "year": 2019,
        "rating": 8.5,
        "genres": ["Thriller", "Drama", "Comedy"],
        "moods": ["Dark", "Mind-Bending", "Philosophical"],
        "director": "Bong Joon Ho",
        "duration": "2h 12m",
        "overview": "Two families from opposite social classes become dangerously intertwined.",
        "poster": "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&auto=format&fit=crop&q=80",
        "backdrop": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1600&auto=format&fit=crop&q=80",
        "streaming": ["Hulu", "Max"],
    },
    {
        "id": "m12",
        "title": "Blade Runner 2049",
        "type": "Movie",
        "year": 2017,
        "rating": 8.0,
        "genres": ["Sci-Fi", "Mystery", "Drama", "Action"],
        "moods": ["Moody", "Philosophical", "Mind-Bending"],
        "director": "Denis Villeneuve",
        "duration": "2h 44m",
        "overview": "A discovery sends a young blade runner searching for a missing officer.",
        "poster": "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80",
        "backdrop": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
        "streaming": ["Max", "Hulu"],
    },
]